### PR TITLE
add compatibility com.diffplug.eclipse.apt

### PR DESCRIPTION
**Pull request by Sirttas**
Currently MG uses gradle task copied from `com.diffplug.eclipse.apt`. this PR turn them off if this plugin is present.

It also adds a warning when to recommend the uses of `com.diffplug.eclipse.apt` over theses tasks.

### CODE REVIEW

**Comment by Sirttas** [comment]
I just saw I still need to add args before it get merged.

**Comment by Mumfrey** [comment]
> Currently MG uses gradle task copied from `com.diffplug.eclipse.apt`. this PR turn them off if this plugin is present.

Why does turning them off make sense? Wouldn't it be more compatible to merge the changes if the other plugin is present?

Please also squash your changes to a single commit.

**Comment by Sirttas** [comment]
> Why does turning them off make sense? Wouldn't it be more compatible to merge the changes if the other plugin is present?

I really do need to better describe my PRs. The idea here came from zml on forge's discord.

Currently both of those tasks are broken for gradle 7. zml suggested to use `com.diffplug.eclipse.apt` over them.

So this PR add this compatibility by doing a few things:
- disable the factory path task
- change the jdt apt task to enrich the one from the `com.diffplug.eclipse.apt` plug-in
- add a warning to recommend using that plug-in when it's not found

I also noticed that `disableEclipseAddon` was not working so I fixed it too.

> Please also squash your changes to a single commit.

You can 'squash and merge' a pull request. I'll squash it when I get back on a computer.

**Comment by Mumfrey** [comment]
> I really do need to better describe my PRs. The idea here came from zml on forge's discord.

Yes



> So this PR add this compatibility by doing a few things:
> 
>     * disable the factory path task
> 
>     * change the jdt apt task to enrich the one from the `com.diffplug.eclipse.apt` plug-in
> 
>     * add a warning to recommend using that plug-in when it's not found

This makes more sense and should have been in the original PR description.





> You can 'squash and merge' a pull request. I'll squash it when I get back on a computer.

Only if you do so via the github web interface and I do not use that for git management tasks, hence the request for the commits to be squashed in the PR itself. Squashing them locally fails to auto-close the PR as merged.

**Comment by Sirttas** [comment]
> Please also squash your changes to a single commit.

Done.

**Comment by DarkShadow44** [comment]
Any news on this? Would be really useful to have for my mod.

**Comment by DarkShadow44** [comment]
What's the state on this?

**Comment by Mumfrey** [comment]
Resolved by #49

**Pull request closed without merging**
